.PHONY	: all install clean tags dist userdoc devdoc
# DO NOT EDIT THIS FILE -- it was generated by configure.py
# configure.py

all: tags
	C:\Python27\python.exe setup.py build

dist:
	C:\Python27\python.exe setup.py sdist

install: tags
	C:\Python27\python.exe setup.py install

clean:
	rm -Rf build
	rm -f tags

tags:
	ctags -R src || true

tests:
	echo "running tests"
	find ./test -type f -name "*.py" -exec python {} \;
